---
  - name: Installing and launching Filebeat
    hosts: elk
    become: yes
    tasks:

    - name: Download .deb file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

    - name: Install .deb file 
      command: dpkg -i filebeat-7.6.1-amd64.deb

    - name: Drop in filebeat.yml
      copy:
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Enable system modules
      command: filebeat modules enable system

    - name: Setup Filebeat
      command: service filebeat start

